from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
import time

driver = webdriver.Chrome("C:\\Users\\ANJUM\\Travel Management System\\Drivers\\chromedriver.exe")
driver.set_page_load_timeout(10)
driver.get("https://www.phptravels.net/admin")
driver.implicitly_wait(5)
driver.maximize_window()
driver.find_element_by_xpath("//form[@class='form-signin form-horizontal wow fadeIn animated animated']//input[@placeholder='Email']").send_keys("admin@phptravels.com")
time.sleep(3)
driver.find_element_by_xpath("//input[@placeholder='Password']").send_keys("demoadmin")
time.sleep(3)
driver.find_element_by_xpath("//button[@class='btn btn-primary btn-block ladda-button fadeIn animated']").click()
time.sleep(3)
driver.find_element_by_xpath("//a[contains(text(),'Modules')]").click()
time.sleep(3)
driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[2]/td[3]/button[1]").click()
time.sleep(3)
driver.find_element_by_xpath("//div[contains(@class,'smartAlertButton smartAlertActive')]").click()
time.sleep(10)
# driver.find_element_by_xpath("//body[contains(@class,'pace-done')]/div[@class='wrapper']/nav[@id='sidebar']/div[@class='social-sidebar']/ul[@id='social-sidebar-menu']/li[7]/a[1]").click()
# time.sleep(1)
# driver.find_element_by_xpath("//a[contains(text(),'Routes')]").click()
# driver.explicitly_wait(10)

#ADD the flights
driver.find_element_by_xpath("//button[contains(text(),'Add')]").click()
time.sleep(1)
driver.find_element_by_xpath("//input[@name='total_hours']").send_keys("12")
time.sleep(1)
driver.find_element_by_xpath("//input[@name='tax']").send_keys("5")
time.sleep(1)
driver.find_element_by_xpath("//input[@name='adultprice[]']").send_keys("25000")
time.sleep(1)
driver.find_element_by_xpath("//div[@id='s2id_locationlist_0']//b").click()
time.sleep(5)
driver.find_element_by_xpath("/html[1]/body[1]/div[10]/div[1]/input[1]").send_keys("Black")
time.sleep(5)
act = ActionChains(driver)
act.send_keys(Keys.ENTER).perform()
time.sleep(1)
driver.find_element_by_xpath("//div[@id='s2id_aeroplanes_0']//span[@class='select2-chosen'][contains(text(),'Enter Arline Name')]").click()
time.sleep(5)
driver.find_element_by_xpath("/html[1]/body[1]/div[11]/div[1]/input[1]").send_keys("Aeroflot")
time.sleep(5)
act = ActionChains(driver)
act.send_keys(Keys.ENTER).perform()
time.sleep(5)
driver.find_element_by_xpath("//tr[1]//th[4]//input[1]").send_keys("325")
time.sleep(5)
driver.find_element_by_xpath("//tr[1]//th[5]//input[1]").send_keys("16/07/19")
time.sleep(5)
driver.find_element_by_xpath("//tr[1]//th[6]//input[1]").send_keys("01:00AM")
time.sleep(5)

driver.find_element_by_xpath("//tr[1]//th[7]//input[1]").send_keys("12:00PM")
time.sleep(5)
act = ActionChains(driver)
time.sleep(5)
driver.find_element_by_xpath("//div[@id='s2id_locationlist_1']//span[contains(@class,'select2-chosen')][contains(text(),'Enter City Or Airport')]").click()
time.sleep(5)
driver.find_element_by_xpath("//div[@id='select2-drop']//input[contains(@class,'select2-input')]").send_keys("quo")
time.sleep(5)
act = ActionChains(driver)
act.send_keys(Keys.ENTER).perform()
time.sleep(5)

driver.find_element_by_xpath("//tr[2]//th[4]//input[1]").send_keys("325")
time.sleep(5)
driver.find_element_by_xpath("//tr[2]//th[5]//input[1]").send_keys("16/07/19")
time.sleep(5)
driver.find_element_by_xpath("//tr[2]//th[6]//input[1]").send_keys("2:30PM")
time.sleep(5)
driver.find_element_by_xpath("//tr[2]//th[7]//input[1]").send_keys("4:00PM")
time.sleep(5)
act = ActionChains(driver)
driver.find_element_by_xpath("//button[@id='add']").click()
time.sleep(5)

#Edit the flights
driver.find_element_by_xpath("//a[contains(@class,'btn btn-default btn-xcrud btn btn-warning')]").click()
time.sleep(5)
driver.find_element_by_xpath("//input[@name='total_hours']").clear()
time.sleep(5)
driver.find_element_by_xpath("//input[@name='total_hours']").send_keys("15")
time.sleep(5)
driver.find_element_by_xpath("//button[@id='manage']").click()

#Delete the flights
# driver.find_element_by_xpath("//a[@id='51']").click()
# time.sleep(5)
# driver.switch_to.alert.accept()
# time.sleep(5)

driver.close()
